# Generated by Django 4.1.3 on 2023-01-08 04:57

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('teamid', models.AutoField(db_column='TeamID', primary_key=True, serialize=False)),
                ('teamname', models.CharField(db_column='TeamName', max_length=40)),
                ('teamrank', models.IntegerField(db_column='TeamRank')),
                ('noofdraws', models.IntegerField(blank=True, db_column='NoOfDraws', null=True)),
                ('noofwins', models.IntegerField(blank=True, db_column='NoOfWins', null=True)),
                ('nooflosses', models.IntegerField(blank=True, db_column='NoOfLosses', null=True)),
                ('points', models.IntegerField(blank=True, db_column='Points', null=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Umpire',
            fields=[
                ('umpireid', models.AutoField(db_column='umpireID', primary_key=True, serialize=False)),
                ('umpirename', models.CharField(db_column='UmpireName', max_length=30)),
                ('noofmatches', models.IntegerField(blank=True, db_column='NoOfMatches', null=True)),
            ],
            options={
                'db_table': 'umpire',
            },
        ),
        migrations.CreateModel(
            name='Teammanagement',
            fields=[
                ('managerid', models.AutoField(db_column='ManagerID', primary_key=True, serialize=False)),
                ('managername', models.CharField(db_column='ManagerName', max_length=30)),
                ('battingcoach', models.CharField(db_column='BattingCoach', max_length=30)),
                ('bowlingcoach', models.CharField(db_column='BowlingCoach', max_length=30)),
                ('teamid', models.ForeignKey(db_column='teamID', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
            options={
                'db_table': 'teammanagement',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('playerid', models.AutoField(db_column='PlayerID', primary_key=True, serialize=False)),
                ('playername', models.CharField(db_column='PlayerName', max_length=30)),
                ('noofmatches', models.IntegerField(blank=True, db_column='NoOfMatches', null=True)),
                ('runsscored', models.IntegerField(blank=True, db_column='RunsScored', null=True)),
                ('noofsixes', models.IntegerField(blank=True, db_column='NoOfSixes', null=True)),
                ('strikerate', models.FloatField(blank=True, db_column='StrikeRate', null=True)),
                ('noofwickets', models.IntegerField(blank=True, db_column='NoOfWickets', null=True)),
                ('economy', models.FloatField(blank=True, db_column='Economy', null=True)),
                ('bestbowling', models.CharField(blank=True, db_column='BestBowling', max_length=6, null=True)),
                ('nooffours', models.IntegerField(blank=True, db_column='NoOfFours', null=True)),
                ('teamid', models.ForeignKey(db_column='TeamID', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('matchid', models.AutoField(db_column='MatchID', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='Status', max_length=1)),
                ('result', models.CharField(blank=True, max_length=1, null=True)),
                ('location', models.CharField(db_column='Location', max_length=20)),
                ('mdate', models.DateField(db_column='Mdate')),
                ('teama_id', models.ForeignKey(db_column='teamA_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamA', to='home.team')),
                ('teamb_id', models.ForeignKey(db_column='teamb_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamB', to='home.team')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captainid', models.AutoField(db_column='CaptainID', primary_key=True, serialize=False)),
                ('noofmatches', models.IntegerField(blank=True, db_column='NoOfMatches', null=True)),
                ('noofwins', models.IntegerField(blank=True, db_column='NoOfWins', null=True)),
                ('playerid', models.ForeignKey(db_column='PlayerID', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.player')),
                ('teamid', models.ForeignKey(db_column='teamID', on_delete=django.db.models.deletion.CASCADE, to='home.team')),
            ],
            options={
                'db_table': 'captain',
            },
        ),
        migrations.CreateModel(
            name='Umpiredby',
            fields=[
                ('matchid', models.IntegerField(db_column='MatchID', primary_key=True, serialize=False, verbose_name=home.models.Matches)),
                ('umpireid', models.ForeignKey(db_column='UmpireID', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.umpire')),
            ],
            options={
                'db_table': 'umpiredby',
                'unique_together': {('matchid', 'umpireid')},
            },
        ),
        migrations.CreateModel(
            name='Plays',
            fields=[
                ('teamid', models.IntegerField(db_column='TeamID', primary_key=True, serialize=False, verbose_name=home.models.Team)),
                ('matchid', models.ForeignKey(db_column='MatchID', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.matches')),
            ],
            options={
                'db_table': 'plays',
                'unique_together': {('teamid', 'matchid')},
            },
        ),
    ]
