# Generated by Django 4.1.3 on 2023-01-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_matches_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='status',
            field=models.CharField(choices=[('O', 'Match over'), ('N', 'Match not over'), ('C', 'Cancelled/abandoned')], db_column='Status', max_length=1),
        ),
    ]
