# Generated by Django 4.1.3 on 2023-01-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_matches_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='teamrank',
        ),
        migrations.AlterField(
            model_name='team',
            name='noofdraws',
            field=models.IntegerField(blank=True, db_column='NoOfDraws', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='nooflosses',
            field=models.IntegerField(blank=True, db_column='NoOfLosses', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='noofwins',
            field=models.IntegerField(blank=True, db_column='NoOfWins', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(blank=True, db_column='Points', default=0, null=True),
        ),
    ]
