# Generated by Django 4.1.3 on 2023-01-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_team_teamrank_alter_team_noofdraws_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(db_column='TeamName', max_length=40, unique=True),
        ),
    ]
